archive:
  _target_: src.moribs.archives.MOCMAMAEArchive
  # solution_dim: will be filled at runtime, see src/main.py
  objective_dim: 2
  reference_point: [0, 0]
  cells: 1000
  # ranges: will be filled at runtime, see src/main.py
  init_discount: 1e-6
  alpha: 0.1
  bias_sampling: true
  max_pf_size: 10
  hvi_cutoff_threshold: null
  # seed: will be filled at runtime, see src/main.py
  samples: 50000

emitters: ${oc.dict.values:._emitter_dict}
_emitter_dict:
  # All emitter types specified in defaults list should have a key named <ID> here
  # (program will throw an error otherwise when instantiating emitters)
  e1: # This should match the <ID> in the defaults list
    num: 5 # Number of emitters of the type specified by <ID> in the defaults list
    # x0: will be filled at runtime, see src/main.py
    sigma0: 0.5
    ranker: "imp"
    selection_rule: "mu"
    restart_rule: "cycle"
    # batch_size: will be filled at runtime, see src/main.py
    # seed: will be filled at runtime, see src/main.py
  e2: # This should match the <ID> in the defaults list
    num: 0 # Number of emitters of the type specified by <ID> in the defaults list
    # x0: will be filled at runtime, see src/main.py
    sigma0: 0.5
    ranker: "rd"
    selection_rule: "mu"
    restart_rule: 500
    # batch_size: will be filled at runtime, see src/main.py
    # seed: will be filled at runtime, see src/main.py

defaults:
  # Specify types of emitters as emitters@_emitter_dict.<ID>.type: ...
  # <ID> can be anything unique (e.g., e1, e2, etc.)
  - emitters@_emitter_dict.e1.type: evolution_strategy_emitter
  - emitters@_emitter_dict.e2.type: evolution_strategy_emitter
  - _self_
